include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "build/**"
    - ".dart_tool/**"
    - "**/*.py"           # ADD THIS
    - "node-template/**"   # ADD THIS

linter:
  rules:
    - always_declare_return_types
    - avoid_empty_else
    - prefer_final_locals
