version: "3.8"
services:
  kernel-mock:
    image: python:3.11-slim
    command: ["python", "kernel-mock.py", "--host", "0.0.0.0", "--port", "8765"]
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - "8765:8765"
  sample-node:
    image: python:3.11-slim
    command: ["python", "node-template/simple_node.py"]
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - kernel-mock
