[phases]
setup = "flutter"
install = "flutter pub get"
build = "echo 'DeltaOS Core - Flutter package built successfully'"

[start]
cmd = "dart bin/delta_os_core.dart --demo"

[build]
baseImage = "ubuntu:22.04"

[[build.env]]
name = "FLUTTER_ROOT"
value = "/opt/flutter"

[[build.env]]
name = "PUB_CACHE"
value = "/root/.pub-cache"

[build.args]
FLUTTER_VERSION = "3.13.0"
