name: delta_os_core
description: The Coordination Layer Operating System
version: 0.1.0-alpha

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  json_serializable: ^6.7.1
  mockito: ^5.4.0
  test: ^1.24.0
  coverage: ^1.6.0

flutter:
  uses-material-design: true
