name: delta_os_core
description: DeltaOS - Coordination Layer Operating System. Makes solutions work together instead of fighting each other.
version: 0.1.0-alpha
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.7.1
  mockito: ^5.4.0

flutter:
  uses-material-design: true
