global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'delta-api'
    static_configs:
      - targets: ['delta-api:8000']
    metrics_path: /metrics
    scrape_interval: 10s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
