name: Lint and Code Quality

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort pylint mypy bandit
    
    - name: Check code formatting with Black
      run: |
        black --check --diff .
    
    - name: Check import sorting with isort
      run: |
        isort --check --diff .
    
    - name: Lint with flake8
      run: |
        flake8 .
    
    - name: Run pylint
      run: |
        pylint $(find . -name "*.py" | grep -v venv)
    
    - name: Security scan with bandit
      run: |
        bandit -r . -f json
