name: Delta OS Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio
        
    - name: Run basic tests
      run: |
        python -c "import delta_net_async; print('✅ Core modules import successfully')"
        python -c "import ultimate_orchestrator; print('✅ Enhanced modules import successfully')"
        
    - name: Run demo test
      run: |
        timeout 30s python delta_net_async.py || exit 0
        echo "✅ Demo executed without crashes"
        
    - name: Syntax check
      run: |
        python -m py_compile delta_net_async.py ultimate_orchestrator.py
        echo "✅ All files compile successfully"

  integration:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Build Docker test
      run: |
        docker build -t delta-os-test .
        echo "✅ Docker build successful"
